version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./TewiiqPHP:/var/www/html
      - ./TewiiqPHP/uploads:/var/www/html/uploads
      - ./TewiiqPHP/database/tewiiq.db:/var/www/html/database/tewiiq.db
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    restart: unless-stopped


